--SQL DDL for Project Two
CREATE TABLE SCRUM_USERS(
 user_id INT,
 user_fn VARCHAR2(4000),
 user_ln VARCHAR2(4000),
 user_username VARCHAR2(4000) UNIQUE NOT NULL,
 user_password VARCHAR2(4000) NOT NULL,
 SUR_id INT DEFAULT 0 NOT NULL,
 user_email VARCHAR2(4000),
 PRIMARY KEY(user_id),
 FOREIGN KEY(SUR_id) REFERENCES SU_ROLES(SUR_id)
);
/
--lookup table for users, 1-employee, 2-manager
CREATE TABLE SU_ROLES(
 SUR_id INT,
 SUR_name VARCHAR2(4000) UNIQUE,
 PRIMARY KEY(SUR_id)
);
/

CREATE TABLE SCRUM_BOARDS(
 SB_ID INT,
 USER_ID INT NOT NULL,
 SB_NAME VARCHAR2(4000) UNIQUE NOT NULL,
 SB_length INT DEFAULT 14 NOT NULL, --for length of sprint
 SB_START TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --for start date of sprint
 PRIMARY KEY(SB_ID),
 FOREIGN KEY(USER_ID) REFERENCES SCRUM_USERS(USER_ID)
);
/
--lookup table for stories? 1-backlog, 2-TODO, 3-In Progress, 4-Test, 5-Verify, 6-Done (Tentative)
CREATE TABLE SB_LANES(
 SBL_ID INT,
 SBL_NAME VARCHAR2(4000) UNIQUE,
 PRIMARY KEY(SBL_ID)
);
/
CREATE TABLE SB_STORIES(
 SBS_ID INT,
 SB_ID INT NOT NULL,
 SBS_description VARCHAR2(4000),
 SBS_POINTS INT NOT NULL,
 SBL_id INT NOT NULL,
 SBS_FINISHED TIMESTAMP,
 PRIMARY KEY(SBS_id),
 FOREIGN KEY(SB_id) REFERENCES SCRUM_BOARDS(SB_id),
 FOREIGN KEY(SBL_ID) REFERENCES SB_LANES(SBL_ID)
);
/
--for status, 0-incomplete, 1-complete
CREATE TABLE SB_TASKS(
 SBT_ID INT,
 SBS_ID INT NOT NULL,
 SBT_STATUS INT DEFAULT 0 NOT NULL,
 SBT_description VARCHAR2(4000),
 PRIMARY KEY(SBT_id),
 FOREIGN KEY(SBS_id) REFERENCES SB_STORIES(SBS_id)
);
/